### ISSUE TITLE
图形化显示

### ISSUE THREAD

**Issue by LuckyBYR** [ipid/NBodySimulate#1]
麻烦问一下那个mp4中的那种图形化显示的代码是如何实现的呀

**Comment by ipid** [comment]
沉迷考研中，我可以过两天再回你吗

**Comment by LuckyBYR** [comment]
学长，救命！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ipid"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 中午11:23
收件人:&nbsp;"ipid/NBodySimulate"<NBodySimulate@noreply.github.com&gt;;
抄送:&nbsp;"haichaoZhang"<419143446@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ipid/NBodySimulate] 图形化显示 (#1)




沉迷考研中，我可以过两天再回你吗

**Comment by ipid** [comment]
我更新了！（但是我也不太确定能不能跑起来

**Comment by LuckyBYR** [comment]
学长还有当时的实验报告吗...






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ipid"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月23日(星期一) 凌晨0:26
收件人:&nbsp;"ipid/NBodySimulate"<NBodySimulate@noreply.github.com&gt;;
抄送:&nbsp;"haichaoZhang"<419143446@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ipid/NBodySimulate] 图形化显示 (#1)




我更新了！（但是我也不太确定能不能跑起来

**Comment by ipid** [comment]
哈哈哈哈哈哈请自行完成

**Comment by LuckyBYR** [comment]
其实早就自己写完了........，只不过不知道卢本捷到底想要写成啥样的

**Comment by ipid** [comment]
但是我分数给得很低，会误导学弟的
